# Generated by Django 3.2 on 2022-11-10 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('symbol', models.CharField(max_length=100, verbose_name='symbol')),
                ('company_name', models.CharField(max_length=100, verbose_name='company_name')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('publish_date', models.DateTimeField()),
                ('url', models.URLField()),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.FileField(upload_to='crawl/', verbose_name='html')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crawl.post')),
            ],
        ),
    ]
